<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm-button_Enviar Contexto de Usuario</name>
   <tag></tag>
   <elementGuidId>5c13fb93-f22d-49c4-8959-52e56be90004</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/app-dashboard/div/confirm-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>confirm-button.mr-2.disabled.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>confirm-button</value>
      <webElementGuid>52fb9f58-be1d-45a6-8b03-6817bbaa4f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 disabled btn-sm</value>
      <webElementGuid>807738fe-09ea-4ba0-b91e-2310ba9e8338</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Enviar Contexto de Usuario </value>
      <webElementGuid>88649df9-2089-4a61-89e2-be95c272573a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/app-dashboard[1]/div[@class=&quot;justify-content-end d-flex&quot;]/confirm-button[@class=&quot;mr-2 disabled btn-sm&quot;]</value>
      <webElementGuid>66d74f41-70ea-42a9-98e8-3b9748f87d8c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/app-dashboard/div/confirm-button</value>
      <webElementGuid>6a52bca9-d7fd-4740-8812-fe899b121b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inicio'])[2]/following::confirm-button[1]</value>
      <webElementGuid>120e3b58-0a60-400c-b118-4577308196b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Usuarios'])[1]/following::confirm-button[1]</value>
      <webElementGuid>e2f5761b-624f-45f5-95bd-0a1b8b4da74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Empresa'])[2]/preceding::confirm-button[1]</value>
      <webElementGuid>55a8647c-aa55-4882-b9ac-dc12187a4850</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//confirm-button</value>
      <webElementGuid>2de6b7c8-e284-45b4-927d-c639004985a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//confirm-button[(text() = ' Enviar Contexto de Usuario ' or . = ' Enviar Contexto de Usuario ')]</value>
      <webElementGuid>91ba1ee0-a0e2-4fd4-b36d-9ae9d61d1796</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
