<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>confirm-button_Aplicar</name>
   <tag></tag>
   <elementGuidId>a79c022b-6694-4f97-9ec8-141a3fbda482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/app-dashboard/div[2]/div/div[2]/app-lists-widget6/div/div/app-dropdown-menu2/div[3]/div/confirm-button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-dropdown-menu2.menu.menu-sub.menu-sub-dropdown.w-250px.w-md-300px.show > div.px-7.py-5 > div.d-flex.justify-content-end > confirm-button.mr-2.disabled.btn-sm</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>confirm-button</value>
      <webElementGuid>08650e2c-492d-4297-a60b-2aa5494b9650</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-kt-menu-dismiss</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fb86dd14-e856-4621-bed2-bb6753326da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mr-2 disabled btn-sm</value>
      <webElementGuid>4c2f0c7c-e38a-4932-af3b-eb591aaf4d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Aplicar </value>
      <webElementGuid>efe32fd7-c7db-4781-ab65-28adf120dd76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/app-dashboard[1]/div[@class=&quot;row g-5 g-xl-10 mb-5 mb-xl-10&quot;]/div[@class=&quot;row gy-5 g-xl-8&quot;]/div[@class=&quot;col-xl-4&quot;]/app-lists-widget6[@class=&quot;card card-xl-stretch mb-xl-8&quot;]/div[@class=&quot;card-header border-0&quot;]/div[@class=&quot;card-toolbar&quot;]/app-dropdown-menu2[@class=&quot;menu menu-sub menu-sub-dropdown w-250px w-md-300px show&quot;]/div[@class=&quot;px-7 py-5&quot;]/div[@class=&quot;d-flex justify-content-end&quot;]/confirm-button[@class=&quot;mr-2 disabled btn-sm&quot;]</value>
      <webElementGuid>c451db31-7064-4f41-b6d1-9ac072cddef7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/app-dashboard/div[2]/div/div[2]/app-lists-widget6/div/div/app-dropdown-menu2/div[3]/div/confirm-button</value>
      <webElementGuid>4e920ea2-5d10-4339-b5d4-d748a3dc7f64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[2]/following::confirm-button[1]</value>
      <webElementGuid>0d71ee1b-e93d-4c32-9f6e-5f40ecc89dfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='El campo es obligatorio'])[1]/following::confirm-button[1]</value>
      <webElementGuid>43efc523-5a07-4474-a967-a265ffe29431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona Flotillas'])[1]/preceding::confirm-button[1]</value>
      <webElementGuid>03e99bc6-3411-434e-9bba-9e1cc08b09ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-dropdown-menu2/div[3]/div/confirm-button</value>
      <webElementGuid>4022091d-574b-46a8-b1b1-d2c25e63c2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//confirm-button[(text() = ' Aplicar ' or . = ' Aplicar ')]</value>
      <webElementGuid>402a460f-3d3a-488e-ae73-4cefa78173cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
