<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Flota_path4</name>
   <tag></tag>
   <elementGuidId>eb2fadc4-a047-4608-b8f8-f8935f66b639</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='kt_app_content_container']/app-dashboard/div[2]/div/div[2]/app-lists-widget6/div/div/button/app-keenicon/span/span[4]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>app-lists-widget6.card.card-xl-stretch.mb-xl-8 > div.card-header.border-0 > div.card-toolbar > button.btn.btn-sm.btn-icon.btn-color-primary.btn-active-light-primary > app-keenicon[name=&quot;category&quot;] > span.fs-2.ki-category.ki-duotone > span.path4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>87cf8362-e251-42e9-9ead-cde04e07885f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path4</value>
      <webElementGuid>007d3a2f-4074-4a89-a78b-4f9ba1142704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;kt_app_content_container&quot;)/app-dashboard[1]/div[@class=&quot;row g-5 g-xl-10 mb-5 mb-xl-10&quot;]/div[@class=&quot;row gy-5 g-xl-8&quot;]/div[@class=&quot;col-xl-4&quot;]/app-lists-widget6[@class=&quot;card card-xl-stretch mb-xl-8&quot;]/div[@class=&quot;card-header border-0&quot;]/div[@class=&quot;card-toolbar&quot;]/button[@class=&quot;btn btn-sm btn-icon btn-color-primary btn-active-light-primary&quot;]/app-keenicon[@class=&quot;fs-2&quot;]/span[@class=&quot;fs-2 ki-category ki-duotone&quot;]/span[@class=&quot;path4&quot;]</value>
      <webElementGuid>1d3ab6f1-da3d-4cbe-b123-41c649622e98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='kt_app_content_container']/app-dashboard/div[2]/div/div[2]/app-lists-widget6/div/div/button/app-keenicon/span/span[4]</value>
      <webElementGuid>97c68859-7db6-4d50-a51a-fab5b6701b9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-lists-widget6/div/div/button/app-keenicon/span/span[4]</value>
      <webElementGuid>d8a99e67-5267-4c6e-bfa7-b0f25c6a4223</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
