<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>XCUIElementTypeKey - more</name>
   <tag></tag>
   <elementGuidId>00000000-0000-0000-0000-000000000000</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>XCUIElementTypeKey</value>
      <webElementGuid>46488181-b83b-4f1a-bbfa-b7ac3549d63c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accessible</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8da31d9b-99c5-4b3d-84f6-d24d30e17632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enabled</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8de6009c-88d4-4238-8bdb-9f1b98da7e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>92.0</value>
      <webElementGuid>8b2fed41-bd1e-4cc2-9413-f4589e51d504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>c7991441-2b99-476b-91c6-794ba2bae768</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>numbers</value>
      <webElementGuid>4c9ee81c-738c-4d37-a7ee-26717004de2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>more</value>
      <webElementGuid>1b38d6b9-4386-428a-8b40-555abea19a66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>196.0</value>
      <webElementGuid>642b9f00-9d58-4d7a-b940-4d4599dc9ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>x</name>
      <type>Main</type>
      <value>0.0</value>
      <webElementGuid>30b918b7-0ce9-4e03-8a6c-e64eae645540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>y</name>
      <type>Main</type>
      <value>1444.0</value>
      <webElementGuid>650b6dd4-507f-44fc-8c7c-48a639dbf5e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeKeyboard[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeKey[28]</value>
      <webElementGuid>b55f311a-1e2b-40ba-bb25-4d5c97522384</webElementGuid>
   </webElementProperties>
   <locator>//*[@type = 'XCUIElementTypeKey' and @label = 'numbers' and @name = 'more']</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
         <value>//*[@type = 'XCUIElementTypeKey' and @label = 'numbers' and @name = 'more']</value>
      </entry>
      <entry>
         <key>NAME</key>
         <value>more</value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value></value>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value>XCUIElementTypeKey</value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value>more</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//XCUIElementTypeApplication/XCUIElementTypeWindow[3]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[4]/XCUIElementTypeKeyboard[1]/XCUIElementTypeOther[1]/XCUIElementTypeOther[1]/XCUIElementTypeKey[28]</value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value>type == 'XCUIElementTypeKey' AND enabled == 1 AND label == 'numbers' AND name == 'more'</value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value>**/XCUIElementTypeKey[`enabled == 1 AND label == 'numbers' AND name == 'more'`]</value>
      </entry>
      <entry>
         <key>ID</key>
         <value>more</value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ATTRIBUTES</locatorStrategy>
   <platform>IOS</platform>
</MobileElementEntity>
